# Generated by Django 5.0.6 on 2024-06-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='realm',
        ),
        migrations.RemoveField(
            model_name='openidconnectprofile',
            name='client',
        ),
        migrations.DeleteModel(
            name='Realm',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
